In [29]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
import glob
import numpy as np

In [23]:
y = ['0','1','2','3','4','5','6','7','8','9','A','a','B','b','C','c','D','d','E','e','F','f','G','g','H','h','I','i','J','j','K','k','L','l','M','m','N','n','O','o','P','p','Q','q','R','r','S','s','T','t','U','u','V','v','W','w','X','x','Y','y','Z','z']; # labels
X = glob.glob("./font/*/*/*.png"); # array of image file paths (features)

In [25]:
def load_and_preprocess_image(file_path):
    # used to read the contents of a file into a tensor. It takes a file path as input and returns a tensor containing the binary data read from the file.
    image = tf.io.read_file(file_path);
    # used to decode an image from a binary string, typically read from a file. It automatically detects the image format and decodes it into a tensor that can be used in TensorFlow.
    image = tf.image.decode_image(image, channels=1); # 1 channel for grayscale, 3 for rgb

    # Preprocess the image (resize, normalize, etc...)
    image = preprocess_image(image);

    return image;

def preprocess_image(image):
    # Explicitly set the shape of the input tensor
    image.set_shape([None, None, 1])
    # Resize
    image = tf.image.resize(image, (224, 224));  # Adjust dimensions as needed

    # Normalized pixel values to the range [0, 1], common practice in image preprocessing for machine learning
    image = image / 255.0;

    return image;

In [38]:
# tensorflow dataset creation
X_tensor = tf.data.Dataset.from_tensor_slices(X);
# applies the function to each element of the dataset X_tensor.
X_tensor = X_tensor.map(load_and_preprocess_image);
print(X_tensor)

<_MapDataset element_spec=TensorSpec(shape=(224, 224, 1), dtype=tf.float32, name=None)>


In [37]:
# Calculate the number of unique labels
num_classes = len(y)

# one-hot encoding method of representing categorical variables as binary vectors. In a one-hot encoded vector, all elements are zero except for one, which is marked with a 1. 
# This is often used to represent classes or categories in a classification problem.
y_one_hot = tf.one_hot(indices=tf.range(len(y)), depth=num_classes)
print(y_one_hot)

tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]], shape=(62, 62), dtype=float32)
